### ISSUE TITLE
Más coverage de Selenium

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1644]
Como desarrollador de omegaUp, quiero poder empujar cambios con la confianza de que en el siguiente push no va a explotar todo.

## Comportamiento Esperado

Todos los escenarios core de la plataforma deberían tener coverage con Selenium y correrse cada vez que se empuja un cambio en Travis:

- [x] Crear un usuario
- [x] Crear un problema
- [x] Crear un concurso https://github.com/omegaup/omegaup/issues/1652
- [x] Crear un curso https://github.com/omegaup/omegaup/issues/1653
- [x] Hacer un envío en un problema #1824 
- [x] Hacer un envío en un concurso
- [x] Hacer un envío en un curso
- [x] Ver el ranking de un concurso https://github.com/omegaup/omegaup/issues/1654
- [x] Ver el ranking de un curso https://github.com/omegaup/omegaup/issues/1655

## Comportamiento Actual

Actualmente tenemos muy poco coverage de la parte de JavaScript.

**Comment by lhchavez** [comment]
Hay que partir este issue en sub-issues.

**Comment by lhchavez** [comment]
Cómo correr las pruebas:

> python3 -m pytest ./frontend/tests/ui/test_archivo.py --disable-headless

(donde `archivo` es `contests`, `schools`, etc.)

Y la documentación de Selenium está acá: http://selenium-python.readthedocs.io/

**Comment by AtharvaKhare** [comment]
Hey @lhchavez , I would like to create a test, suggest me a simple one to start with? I have used selenium before.

**Comment by elendil326** [comment]
Hello @AtharvaKhare . I have just created the issue to cover the last selenium test. Let me know if you want to work on it so I tag it appropriately.

**Comment by AtharvaKhare** [comment]
Yes @elendil326 I would like to work on this issue, thanks!

**Comment by pabo99** [comment]
Ya están cubiertos todos los escenarios planteados aquí, ¿Se consideran agregar más? o ¿podemos cerrar este issue?

**Comment by pabo99** [comment]
This issue is no longer necessary since we have migrated all the JavaScript tests to Cypress.
