### ISSUE TITLE
Smarty template vuefication

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#2009]
This issue is used as master issue to track all vue migration progress
List of smarty template that needs to be converted to `.vue`

### Task 1 [✔️]
Vuefication problem list. These files will take effects : `problems.tpl`, `problem.list.tpl`, `pager_bar.tpl`
[Issue link](https://github.com/omegaup/omegaup/issues/1999) - Assign to @CarlosCordova18 (Completed)

### Task 2 [✔️]
Vuefication arena index. These files will take effects :  `arena.contest_list.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2127), `arena.index.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/3523)

### Task 3
Vuefication arena competition. These files will take effects : `arena.contest.tpl`, `arena.contest.course.tpl`, `arena.contest.admin.tpl`, `arena.contest.practice.tpl`, `arena.contest.practice.tpl`, `arena.contest.interview.tpl`,
`arena.clarification_list.tpl`, `arena.problem.tpl`, 
`arena.runs.tpl`  [PR merged](https://github.com/omegaup/omegaup/pull/3725)

### Task 4 [✔️]
Vuefication contest intro. Only this fill will take effects : `arena.contest.intro.tpl`  [PR merged](https://github.com/omegaup/omegaup/pull/4000)

### Task 5
Vuefication html navbar and header. These files will take effects : `head.tpl`, `common.navbar.tpl` [PR Merged](https://github.com/omegaup/omegaup/pull/2905) , `common.navbar.notifications.tpl` [PR Merged](https://github.com/omegaup/omegaup/pull/2909)

### Task 7 [✔️]
Vuefication contest related tpl. These files will take effects

- [X] `contest.edit.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2127)
- [X] `contest.new.form.tpl` [PR merged](https://github.com/omegaup/omegaup/issues/3925)
- [X] `contest.report.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2295)

### Task 8 [✔️]
Vuefication small graph on omegaup index page. This file will take effects : `contest.stats.tpl`
[PR link](https://github.com/omegaup/omegaup/pull/2087) - Assigned to @sarvesh211999 

### Task 9 [✔️]
Vuefication course related tpl. These files will take effects : `course.list.tpl`[PR merged](https://github.com/omegaup/omegaup/pull/3335), `course.details.tpl`[PR merged](https://github.com/omegaup/omegaup/pull/4150), `course.edit.tpl`[PR merged](https://github.com/omegaup/omegaup/pull/4330)

### Task 10
Vuefication group related tpl. These files will take effects : `group.edit.tpl`, `group.edit.scoreboards.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/4985), `group.edit.members.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2515),  `group.list.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/1186), `group.new.tpl`[PR merged](https://github.com/omegaup/omegaup/pull/4971), `group.scoreboard.details.tpl`, `group.scoreboard.edit.contests.tpl`, `group.scoreboard.edit.tpl`

### Task 11
Vuefication user profile. These files will take effects : `profile.basic.info.tpl`, `profile.tpl`

### Task 12 [✔️]
Vuefication rank. These files will take effects : `rank.table.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2273)

### Task 13
Vuefication user related tpl. These files will take effects : `user.basicedit.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2167), `user.edit.tpl`, `user.email.edit.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/2066) , `user.profile.tpl` [PR merged](https://github.com/omegaup/omegaup/pull/1930)

### Task 14 [✔️]
Vuefication problem edit. These files will take effects: `problem.edit.form.tpl` [Issue link](https://github.com/omegaup/omegaup/issues/2218) - [PR merged](https://github.com/omegaup/omegaup/pull/3786)

NB : For those of you who want to contribute on the vuefication read this [link](https://pastebin.com/5psKRQpH). Special thanks to @CarlosCordova18

**Comment by sarvesh211999** [comment]
@SpaceWhite  Can you please update the list ??
Please tick those files that have been already migrated.

**Comment by SpaceWhite** [comment]
@sarvesh211999 Sure :)

**Comment by pabo99** [comment]
Reabriendo porque faltan aún muchas cosas por migrar.
