### ISSUE TITLE
Separar el scoreboard de los invitados a un concurso y los participantes

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2128]
Esta es la segunda parte de #719. Los concursantes que fueron explícitamente invitados a un concurso deberían tener un scoreboard separado. Así ya podría funcionar al 100% el modo "abierto".

Lo que faltaría sería hacer un toggle / checkbox arriba de los scoreboards en modo abierto y que cuando esté activo, muestre el scoreboard oficial (solo los explícitamente invitados), y cuando no muestre el scoreboard extraoficial (todos).

- [X] Cambio en los controladores para que al regresar el scoreboard, venga con la anotación de si el concursante es oficial o extraoficial, con un cambio en las pruebas de PHPUnit (#2185).
- [x] Cambio en la UI para poder filtrar por oficial / extraoficial en el scoreboard (#2233).
- [x] Prueba de Selenium para el cambio (#2233).

**Comment by kukogit** [comment]
Así que de aquí fue donde salió este feature... baia baia... apenas iba a ser un issue para que lo quitarán... porque creo que no hace lo que debería... yo agregó alumnos a mi concurso y tengo que darle desactivar ese tonto checkbox a cada rato para ver el scoreboard... porque ahh como da lata...

**Comment by kukogit** [comment]
Con la lata me refiero a que no muestra el scoreboard, tengo que desactivar el checkbox con cada F5 que le doy... y la verdad es muy molesto.

**Comment by darkmx** [comment]
Hola a todos.

Yo también encuentro que ese checkbox es problemático. La funcionalidad que provee es buena, pero para concursos públicos (donde uno no suele agregar participantes, sino que ellos entran por su voluntad) tenerlo marcado por omisión no es muy conveniente que digamos. Propongo que si el concurso es público, entonces aparezca no marcado por omisión.
