### ISSUE TITLE
Realizar migración de Javascript a TypeScript en archivos Vue

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2583]
Como desarrollador, quiero que todo el código de Javascript embebido
en  los archivo `Vue` sea sustituido por código en TypeScript esperando
tener un mejor control de los componentes, además porque Javascript
será deprecado.

## Comportamiento Esperado

El plan es ir haciendo el cambio gradualmente hasta cubrir con el 100%
del código migrado.

## Posible Solución

Una posible solución es buscar herramientas que ayuden a realizar este
trabajo. En caso de no encontrar ninguna, se pueden dar de alta issues
por módulos. Los archivos que se tienen que migrar son los siguientes:

- [X] `RankTable.vue` PR #2554 (Aprobado)
- [x] Globales (`Autocomplete.vue`, `CountryFlag.vue`, `DatePicker.vue`, `DateTimePicker.vue`, `DistributionChart.vue`, `VerdictChart.vue`) Issue #2584 - PR's #2604 (Aprobado) y #2776 (Aprobado)
- [x] `activity` (`Feed.vue`, `SubmissionsList.vue`) Issue #2585 - PR #2774 (Aprobado)
- [x] `admin` (`Roles.vue`, `Support.vue`, `User.vue`) Issue #2586, PR #2785 (Aprobado)
- [x] `arena` (`CodeView.vue`, `RunDetails.vue`, `Scoreboard.vue`, `Virtual.vue`) Issue #2587 - PRs #2827 (Aprobado) y #2837 (Aprobado)
- [X] `coderofthemonth` (`CoderOfTheMonth.vue`, `Notice.vue`) Issue #2588 -  PR #2765 (Aprobado)
- [x] `contest` (`AddProblem.vue`, `Admins.vue`, `Clone.vue`, `ContestList.vue`) Issue #2589 - PR #2794 (Aprobado) 
- [x] `contest` (`Contestant.vue`, `Edit.vue`, `GroupsAdmin.vue`, `Links.vue`, `NewForm.vue`) Issue #2590 - PRs #2763 (Aprobado) y  PR #2795  (Aprobado),
- [x] `contest` (`Publish.vue`, `Report.vue`, `Requests.vue`, `ScoreboardMerge.vue`, `Stats.vue`) Issue #2591 -  PR #2767 (Aprobado), PR #2773 (Aprobado)
- [x] `course` (`AddStudents.vue`, `Administrators.vue`, `AssignmentDetails.vue`, `AssignmentList.vue`, `Clone .vue`) Issue #2592 - PR #2791 (Aprobado) 
- [x] `course` (`Details.vue`, `Intro.vue`, `ProblemList.vue`) Issue #2593 - PR #2793 (Aprobado)
- [x] `course` (`ViewProgress.vue`, `ViewStudent.vue`) Issue #2594 - PR's #2811 (Aprobado) y #2891 (Aprobado)
- [x] `group ` (`GroupList.vue`, `Identities.vue`, `Members.vue`) Issue #2595 - PR's #2798 (Aprobado) y  #2839 (Aprobado)
- [X] `identity` (`Edit.vue`) PR #2523 (Aprobado) 
- [x] `problem ` (`Feedback.vue`, `FinderWizard.vue`, `Histogram.vue`) Issue #2596 - PR's #2769 (Aprobado) y #2838 (Enviado)
- [x] `problem ` (`List.vue`, `Stats.vue`, `Versions.vue`) Issue #2597 - PR's #2775 (Aprobado), #2783 (Aprobado), #2792 (Aprobado) 
- [x] `qualitynomination ` (`DemotionPopup.vue`, `Details.vue`, `List.vue`, `Popup.vue`) Issue #2598 - PR #2787 (Aprobado)
- [x] `schools ` (`Intro.vue`, `Rank.vue`) `Issue` #2599, `PR` #2771 (Aprobado) 
- [X] `user ` (`BasicEdit.vue`, `BasicInfo.vue`, `EmailEdit.vue`, `ManageIdentities.vue`, `PrivacyPolicy.vue`, `Profile.vue`, `Username .vue`) Issue #2600 - PR #2633 (Aprobado),  PR #2684 (Aprobado), PR #2693 (Aprobado)
- [x] `user ` (`Charts.vue`) `Issue` #2601 - PR #2892 (Aprobado)

**Comment by pabo99** [comment]
Se han migrado todos los componentes a TypeScript. Ya se puede cerrar este issue.
