### ISSUE TITLE
Migración a Typescript de los componentes globales

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2584]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
globales.

En este issue se contempla la migración de:

- [X] `Autocomplete.vue` PR #2604 (Aprobado)
- [X] `CountryFlag.vue` PR #2604 (Aprobado)
- [X] `DatePicker.vue` PR #2604 (Aprobado)
- [X] `DateTimePicker.vue` PR #2604 (Aprobado)
- [ ] `DistributionChart.vue` PR #2776 (En Revisión)
- [ ] `VerdictChart.vue` PR #2776 (En Revisión)
