### ISSUE TITLE
Migración a Typescript de los componentes de admin

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2586]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `admin`.

En este issue se contempla la migración de:

- [ ] `Roles.vue` PR #2785 (En revisión) 
- [ ] `Support.vue` PR #2785 (En revisión)
- [ ] `User.vue` PR #2785 (En revisión)
