### ISSUE TITLE
Migración a Typescript de los componentes de contest (parte 1)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2589]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `contest` parte 1.

En este issue se contempla la migración de:

- [ ] `AddProblem.vue` PR #2794 (Enviado)
- [ ] `Admins.vue` PR #2794 (Enviado)
- [ ] `Clone.vue` PR #2794 (Enviado)
- [ ] `ContestList.vue` PR #2794 (Enviado)
