### ISSUE TITLE
Migración a Typescript de los componentes de contest (parte 2)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2590]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `contest` parte 2.

En este issue se contempla la migración de:

- [x] `Contestant.vue`  PR #2763  (Aprobado)
- [ ] `Edit.vue`  PR #2795  (Enviado)
- [ ] `GroupsAdmin.vue` PR #2795  (Enviado)
- [ ] `Links.vue` PR #2795  (Enviado)
- [ ] `NewForm.vue` PR #2795  (Enviado)
