### ISSUE TITLE
Migración a Typescript de los componentes de contest (parte 3)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2591]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `contest` parte 3.

En este issue se contempla la migración de:

- [x] `Publish.vue` PR #2773 (Aprobado)
- [X] `Report.vue`  PR #2767 (Aprobado)
- [x] `Requests.vue` PR #2773 (Aprobado)
- [x] `ScoreboardMerge.vue` PR #2773 (Aprobado)
- [x] `Stats.vue` PR #2773 (Aprobado)
