### ISSUE TITLE
Migración a Typescript de los componentes de course (parte 2)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2593]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `course` parte 2.

En este issue se contempla la migración de:

- [ ] `Details.vue` PR #2793 (En revisión)
- [ ] `Intro.vue` PR #2793 (En revisión)
- [ ] `ProblemList.vue` PR #2793 (En revisión)
