### ISSUE TITLE
Migración a Typescript de los componentes de problem (parte 2)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2597]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `problem` parte 2.

En este issue se contempla la migración de:

- [x] `List.vue` PR #2775 (Aprobado)
- [ ] `Stats.vue` PR #2792 (Enviado)
- [x] `Versions.vue` PR #2783  (Aprobado)
