### ISSUE TITLE
Migración a Typescript de los componentes de qualitynomination

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2598]
Como parte de la migración de los componentes `vue` de `Javascript` a 
`Typescript` se da de alta este issue para dar seguimiento a los componentes
de `qualitynomination `.

En este issue se contempla la migración de:

- [ ] `DemotionPopup.vue` PR #2787 (En Revisión)
- [ ] `Details.vue` PR #2787 (En Revisión)
- [ ] `List.vue` PR #2787 (En Revisión)
- [ ] `Popup.vue` PR #2787 (En Revisión)

**Comment by carlosabcs** [comment]
@pabo99 para evitar trabajar en lo mismo, dejo este comentario para que sepas que tomaré este issue :D

**Comment by pabo99** [comment]
> @pabo99 para evitar trabajar en lo mismo, dejo este comentario para que sepas que tomaré este issue :D

Excelente idea. También te lo asigné para evitar tomar el mismo issue
