### ISSUE TITLE
[Refactor de Identidad] Mantener integridad de los datos entre usuario e identidad

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2608]
Con la nueva funcionalidad de Identidades, es posible que se pierda la integridad
de la información, ya que las dos tablas (`Identities` y `Users`) cuentan con la
los datos personales del usuario. Hay que cerciorarse que la información en las
dos siempre es la misma.

## Comportamiento Actual

La información se guarda en las dos tablas, y cada que se edita el perfil del 
usuario, esta información se replica en la tabla de identidades.

## Posible Solución

La mejor solución sería borrar la información duplicada, esto le afectará al código
donde se manda llamar, habrá que revisar todos los lugares donde se utilizan los 
campos que se eliminen.

Los campos a eliminar en la tabla `Users` son los siguientes:

 - [ ] `name`, `gender` y `school_id` #2649 
 - [ ] `language_id` - `PR`: #2645 
 - [ ] `state_id` y `country_id` - PR #2652 

Posiblemente se divida en varios `Pull Requests`.

**Comment by pabo99** [comment]
Uno de los datos que se duplica en las dos tablas es `gender`, puesto a que las identidades
se dan de alta por batch, lo más recomendable es mantener este campo en la tabla de 
usuarios, ya que esta información tendría que solamente debería de dar la persona que se
está registrando directamente.

¿Cuál es su opinion?

**Comment by lhchavez** [comment]
si un usuario desea identificarse con un género distinto al que le asignó el administrador del clncurso, no deberíamos detenerlo.

**Comment by pabo99** [comment]
Enterado, el campo se queda en la tabla de identidades.

Gracias.
