### ISSUE TITLE
[Refactor de Identidad] Agregar pruebas unitarias para Identidades

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2651]
Como un desarrollador, quiero que se cubran las pruebas de identidades para
asegurarme de que no habrán fallas en producción.

## Comportamiento Esperado

Ahora que ya está por liberarse el Refactor de Identidad, debemos garantizar que
todo funcione correctamente, para ello habrá que validar esto desde las pruebas
 en `PHPUnit`:

 #### La identidad puede:

 - [X]  Ser creada desde Grupos. PR #2140 
 - [X] Ser asociada a una cuenta de usuario. #2164 
 - [X] Ser editada desde la cuenta del creador del grupo #2162
 - [X] Ingresar a omegaUp sin haber sido asociada. PR #2192 
 - [X] Ingresar a omegaUp después de haber sido asociada. #2656
 - [X] Ingresar a un concurso público. #2656
 - [X] Ser invitada a un concurso privado. #2656
 - [X] Ingresar a un concurso privado al cual fue invitada. #2656
 - [X] Enviar una solución a cualquier problema. #2656
 - [ ] Ingresar a un curso para el grupo que fue creada. #2662 

 #### La identidad no puede:

 - [ ] Crear concursos. #2663
 - [ ] Clonar concursos. #2663
 - [ ] Crear concursos virtuales. #2663
 - [ ] Crear cursos. #2663
 - [ ] Clonar cursos. #2663
 - [ ] Crear problemas. #2663
 - [ ] Ver la lista de concursos creados. #2663
 - [ ] Ver la lista de problemas creados. #2663
