### ISSUE TITLE
[Refactor de Identidad] Agregar pruebas automatizadas para Identidades

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2664]
Agregar las pruebas automatizadas de `Selenium` que cubran todo lo referente a identidades.

 #### La identidad puede:

 - [X] Ser creada desde grupos. `PR` #2697 (Aprobado)
 - [x] Ser asociada a una cuenta de usuarios. `PR` #2723 (Aprobado)
 - [x] Ingresar a omegaUp sin haber sido asociada. `PR` #2723 (Aprobado)
 - [x] Ingresar a omegaUp después de haber sido asociada. `PR` #2723 (Aprobado)
 - [x] Ingresar a un concurso público. `PR` #2723 (Aprobado)
 - [x] Ser invitada a un concurso privado. `PR` #2723 (Aprobado)
 - [x] Ingresar a un concurso privado al cual fue invitada. `PR` #2723 (Aprobado)
 - [x] Enviar una solución a cualquier problema.  `PR` #2723 (Aprobado)
 - [x] Ingresar a un curso para el grupo que fue creada.  `PR` #2723 (Aprobado)

 #### La identidad no puede:

 - [ ] Crear concursos. `PR` #2749 (Enviado)
 - [ ] Crear cursos. `PR` #2749 (Enviado)
 - [ ] Crear problemas. `PR` #2749 (Enviado)
 - [ ] Ver la lista de concursos creados. `PR` #2749 (Enviado)
 - [ ] Ver la lista de problemas creados. `PR` #2749 (Enviado)

**Comment by pabo99** [comment]
Bloqueado hasta que apaguemos el experimento de `Identities`

**Comment by pabo99** [comment]
Buscar la forma de apagar experimento mientras se realiza la prueba, una opción es verificando a los usuarios
