### ISSUE TITLE
[FEATURE] Vuefication arena competition: arena.problem.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3489]
Smarty template `arena.problem.tpl` needs to be converted to .vue

This issue will be separated in the following changes:

- [X] Create component: Setting Summary BS4 version  (Issue #3489 - PR #4481 Approved)
- [x] Add more elements to the payload (Issue #4483 - PR #4494 Approved)
- [x] Create component: Best Solvers (Issue #4488 - PR #4495 Approved)
- [x] [UI] Add components in the Problem tab (Issue #4489 - PR #4497 Approved)
- [x] [UI] Add solutions component (Issue #4490)
- [x] [UI] Add admin runs component (Issue #4491)
- [x] [UI] Add clarifications component (Issue #4492)
- [X] Add all needed handlers (Issue #4511 - PRs #4518 and #4519 Approved)
- [x] Connect with Arena and remove legacy code (Issue #4493 - PR #4966 Approved)
- [ ] Migrate to unified template (PR #4986 In Review)

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)
