### ISSUE TITLE
GSoC '24 - Migrate Problem Creator to Vue.js + Typescript

### ISSUE THREAD

**Issue by Aritra8438** [omegaup/omegaup#7586]
This summer, my mentor  @carlosabcs  and I will complete the project [`Migrate Problem Creator to Vue.js + Typescript`](https://summerofcode.withgoogle.com/programs/2024/projects/tEAcN96u) as part of GSoC '24.
[Here](https://summerofcode.withgoogle.com/programs/2024/projects/tEAcN96u) is the official announcement of the project.

Here is the meta issue tracker for the project.
---
| Issue  | PR | Status |
| ------------- | ------------- | --------------|
| Add markdown editor to the writing (problem statement) tab and write vue tests for it  |  | --- |
| Add markdown editor to the writing (problem statement) tab and write vue tests for it  |  | --- |
| Add markdown editor to the writing (problem statement) tab and write vue tests for it  |  | --- |
- [x] [Support for `max` aggregation function while summarizing columns | mathesar#2909](https://github.com/centerofci/mathesar/issues/2909)
- [x] [Support for `min` aggregation function while summarizing columns | mathesar#2913](https://github.com/centerofci/mathesar/issues/2913)
- [x] [Support for `mean` aggregation function while summarizing columns | mathesar#2915](https://github.com/centerofci/mathesar/issues/2915)
- [x] [Support for `median` aggregation function while summarizing columns | mathesar#2931](https://github.com/centerofci/mathesar/issues/2931)
- [x] [Support for `mode` aggregation function while summarizing columns | mathesar#2918](https://github.com/centerofci/mathesar/issues/2918)
- [x] [Support for `percentage-true` aggregation function while summarizing columns | mathesar#2944](https://github.com/centerofci/mathesar/issues/2944)
- [x] [Support for `Peak time` aggregation function while summarizing columns | mathesar#2980](https://github.com/centerofci/mathesar/issues/2980)
- [x] [Support for `Peak month` aggregation function while summarizing columns | mathesar#3005](https://github.com/centerofci/mathesar/issues/3005)
- [x] [Fix the error when `list aggregation` on mathesar custom array | mathesar#3106](https://github.com/centerofci/mathesar/pull/3106)

**Comment by carlosabcs** [comment]
LGTM, you can start the coding phase!
